FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
ARG BUILD_CONFIGURATION=Release
COPY *.sln .
COPY /api/SO-tags.csproj ./api/SO-tags.csproj
COPY /apiTests/apiTests.csproj ./apiTests/apiTests.csproj

RUN dotnet restore

COPY /api ./api
COPY /apiTests ./apiTests

WORKDIR /app/api
RUN dotnet build -c $BUILD_CONFIGURATION -o /app/build

#FROM build as tests
WORKDIR /app
RUN dotnet test --configuration=Release


FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "/app/api/SO-tags.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
#CMD [ "dotnet", "SO-tags.dll"]
ENTRYPOINT ["dotnet", "SO-tags.dll"]